{"timestamp":"2025-08-19T17:32:18.887188","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-19T17:32:19.012327","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/ELT.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-19T17:32:39.636733","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py:147: DeprecationWarning: Using Variable.get from `airflow.models` is deprecated.Please use `from airflow.sdk import Variable` instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-19T17:32:39.996780","level":"info","event":"Done. Returned value was: ['/opt/airflow/data/children.csv', '/opt/airflow/data/consumption.csv', '/opt/airflow/data/ingredients.csv', '/opt/airflow/data/meals.csv']","logger":"airflow.task.operators.airflow.providers.standard.decorators.python._PythonDecoratedOperator"}
{"timestamp":"2025-08-19T17:32:39.999284","level":"info","event":"Pushing xcom","ti":"RuntimeTaskInstance(id=UUID('0198c363-3080-7266-8509-1ae1cf3955ab'), task_id='get_input_files_list', dag_id='ELT_pipeline_com_postgres', run_id='manual__2025-08-19T17:31:54.323850+00:00', try_number=1, map_index=-1, hostname='dab8c10d698c', context_carrier={}, task=<Task(_PythonDecoratedOperator): get_input_files_list>, bundle_instance=LocalDagBundle(name=dags-folder), max_tries=0, start_date=datetime.datetime(2025, 8, 19, 17, 32, 1, 956918, tzinfo=datetime.timezone.utc), end_date=None, state=<TaskInstanceState.RUNNING: 'running'>, is_mapped=False, rendered_map_index=None, log_url='http://localhost:8080/dags/ELT_pipeline_com_postgres/runs/manual__2025-08-19T17%3A31%3A54.323850%2B00%3A00/tasks/get_input_files_list?try_number=1')","logger":"task"}
{"timestamp":"2025-08-19T17:33:41.148055","level":"error","event":"Top level error","logger":"task","error_detail":[{"exc_type":"AirflowRuntimeError","exc_value":"API_SERVER_ERROR: {'status_code': 409, 'message': 'Server returned error', 'detail': {'detail': {'reason': 'invalid_state', 'message': 'TI was not in the running state so it cannot be updated', 'previous_state': 'success'}}}","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1313,"name":"main"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":967,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py","lineno":203,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py","lineno":263,"name":"_get_response"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py","lineno":250,"name":"_from_frame"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-19T17:33:41.308742Z","level":"warning","event":"Process exited abnormally","exit_code":1,"logger":"task"}
